# Generated by Django 4.0.5 on 2022-06-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('US', 'Usuario Comun'), ('CL', 'Cliente'), ('AD', 'Administrador Instalaciones'), ('AA', 'Administrador Aeropuertos'), ('AR', 'Administrador Reparaciones')], default='US', max_length=2)),
            ],
        ),
    ]
