# Generated by Django 4.0.5 on 2022-06-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_usuario_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
